spring:
  application:
    name: ordersystem
  jpa:
    show-sql: 'true'
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/ordersystem_db
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Durability & Ordering Garantileri:
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
    consumer:
      group-id: ${kafka.consumer.group-id}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
outbox:
  publisher:
    batch-size: 100
    lease-duration-seconds: 60
    fixed-delay-ms: 1000
    topic: order-events
    publish-timeout-seconds: 5

kafka:
  consumer:
    topic: order-events
    group-id: order-system-shipment-consumer